baseurl: http://liyingbo.com
title: King Fox And Butterfly
theme: hugo-creative-portfolio-theme
languageCode: en-us
googleAnalytics: 'UA-116913878-1'
disqusShortname: 'kfab'
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  copyright: '&copy; Yingbo Li 2018 -- 2021'
  description: A blog about cooking and statistics.
  email: you@yoursite.com
  navlinks:
    - home: yes
      name: Cooking
      url: cooking/
    - name: Statistics
      url: stat/
    - name: About Me
      url: about/
    - name: Categories
      url: categories/
    - name: Tags
      url: tags/
  sidebarAbout:
    - I am a home cook and statistian, both with more than 10 years of
      experience.
    - Originally from Shanghai, currently based in Dallas.
  social:
    github: https://github.com/yingboli
    linkedin: https://www.linkedin.com/in/yingbo-li-08321723/
  style: blue

