baseurl: http://liyingbo.com
languageCode: en-us
title: King Fox And Butterfly
theme: hugo-xmin
googleAnalytics: 'UA-116913878-1'
disqusShortname: 'kfab'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
  cooking: /cooking/:year/:month/:day/:slug/
  life: /life/:year/:month/:day/:slug/
  stat: /stat/:year/:month/:day/:slug/

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About Me
      url: /about/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: Subscribe
      url: index.xml
      weight: 5

params:
  description: "A blog about cooking and statistics."
  footer: "&copy; [Yingbo Li](https://liyingbo.com) 2018 -- 2021 | [Github](https://github.com/yingboli) | [Linkedin](https://www.linkedin.com/in/yingbo-li-08321723/)"

markup:
  goldmark:
    renderer:
      unsafe: true
