baseurl: http://liyingbo.com
languageCode: en-us
title: King Fox And Butterfly
theme: hugo-lithium
googleAnalytics: 'UA-116913878-1'
disqusShortname: 'kfab'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
  cooking: /cooking/:year/:month/:day/:slug/
  life: /life/:year/:month/:day/:slug/
  stat: /stat/:year/:month/:day/:slug/

menu:
  main:
    - name: Cooking
      url: /cooking/
      weight: 1
    - name: Statistics
      url: /stat/
      weight: 2
    - name: Life
      url: /life/
      weight: 3
    - name: About Me
      url: /about/
      weight: 4
    - name: Categories
      url: /categories/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 6

params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A blog for cooking and statistics.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: yingbo_headshot.jpg
    width: 50

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
